version: '3'

services:
  website:
    build:
      context: .
      dockerfile: MLwelding_seams/docker/flask.Dockerfile
    ports:
      - "5000:5000"
    restart: always

  telegram-bot:
    build:
      context: .
      dockerfile: MLwelding_seams/docker/tg.Dockerfile
    restart: always
    environment:
      - BOT_TOKEN= '7064403736:AAFNUPLB4VGSNctsDm8QBijLX7C50F0SjYg'
