version: '3'

services:
  website:
    build:
      context: .
      dockerfile: flask.Dockerfile
    ports:
      - "8000:8000"
    restart: always

  telegram-bot:
    build:
      context: .
      dockerfile: tg.Dockerfile
    restart: always
    environment:
      - BOT_TOKEN= '7064403736:AAFNUPLB4VGSNctsDm8QBijLX7C50F0SjYg'
